name: zettle
description: A wrapper for the Zettle POS SDK for Android and iOS. Includes support for charging and refunding.
version: 0.2.15
repository: https://github.com/ovatu/zettle_flutter
homepage: https://ovatu.com/us
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.ovatu.zettle
        pluginClass: ZettlePlugin
      ios:
        pluginClass: ZettlePlugin
